# 使用 Node.js 18 镜像
FROM node:18-alpine

# 设置工作目录
WORKDIR /app

# 复制 package 文件
COPY package*.json ./

# 安装所有依赖（包括 devDependencies，构建需要）
RUN npm ci

# 复制源代码
COPY . .

# 接收构建时的环境变量
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_DINGTALK_APP_KEY
ARG VITE_DINGTALK_APP_SECRET
ARG VITE_DINGTALK_AGENT_ID
ARG VITE_DINGTALK_CORP_ID
ARG VITE_DINGTALK_ENCODING_AES_KEY

# 设置为环境变量供 Vite 构建时使用
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_DINGTALK_APP_KEY=$VITE_DINGTALK_APP_KEY
ENV VITE_DINGTALK_APP_SECRET=$VITE_DINGTALK_APP_SECRET
ENV VITE_DINGTALK_AGENT_ID=$VITE_DINGTALK_AGENT_ID
ENV VITE_DINGTALK_CORP_ID=$VITE_DINGTALK_CORP_ID
ENV VITE_DINGTALK_ENCODING_AES_KEY=$VITE_DINGTALK_ENCODING_AES_KEY

# 构建前端
RUN npm run build

# 删除 devDependencies 以减小镜像大小
RUN npm prune --production

# 暴露端口
EXPOSE 3000

# 启动命令：运行 Express 服务器（同时服务前端和 API）
CMD ["node", "server/railway-server.js"]

